config/routes.rb
Rails.application.routes.draw do
  resources :songs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "songs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/song.rb
class Song < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: %i[ show edit update destroy ]

  # GET /songs or /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to song_url(@song), notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to song_url(@song), notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy!

    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:title, :speed, :description, :bol)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taalmaster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-2 px-2 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/songs/_form.html.erb
<div data-controller="songs">
  <%= form_with(model: song, class: "contents") do |form| %>
    <% if song.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>
        <ul>
          <% song.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <%= form.label :title %>
      <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :speed %>
      <%= form.text_field :speed, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :description %>
      <%= form.text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <%= form.hidden_field :bol, data: {"songs-target": "songBol"} %>

    <%# This is the main notes container %>
    <div class="my-4">
      <div data-songs-target="notesContainer"
        class="grid grid-cols-4 md:grid-cols-8 lg:grid-cols-16 gap-2 font-mono text-white text-sm text-center font-bold leading-6 bg-stripes-fuchsia rounded-lg">
      </div>
    </div>

    <div class="inline">
      <%= form.submit "Save",
        class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>

  <template data-songs-target="noteTemplate">
    <div class="note p-4 rounded-lg shadow-lg bg-fuchsia-500 relative">
      <div class="note-content"></div>
      <button class="absolute -top-2 -right-2" data-action="songs#deleteSongNote">
        <svg class="w-6 h-6" fill="black" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
        </svg>
      </button>
    </div>
  </template>

  <div class="mt-4">Click on the bols below to add to the song</div>
  <div class="my-4 grid grid-cols-1 gap-4">
    <%
      bol_groups = [
        %w(Dha Dhin S),
        %w(Ke Ge),
        %w(Ti Ta),
        %w(Na Ta Tin Tun),
        %w(Tira Kita),
        %w(TiraKita)
      ]
    %>
    <% bol_groups.each do |group| %>
      <div class="grid grid-cols-4 md:grid-cols-8 lg:grid-cols-16 gap-2 font-mono text-white text-sm text-center font-bold leading-6 bg-stripes-fuchsia rounded-lg">
        <% group.each do |bol| %>
          <button class="p-4 rounded-lg shadow-lg bg-fuchsia-500" data-action="songs#addSongNote"><%= bol %></button>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/songs/_song.html.erb
<div id="<%= dom_id song %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= song.title %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= song.description %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Speed:</strong>
    <%= song.speed %>
  </p>

  <div class="my-5">
    <strong class="block font-medium mb-1">Bol:</strong>
    <div class="grid grid-cols-4 md:grid-cols-8 lg:grid-cols-16 gap-2 font-mono text-white text-sm text-center font-bold leading-6 bg-stripes-fuchsia rounded-lg">
      <% song.bol.split(",").map(&:strip).each do |bol| %>
        <div class="p-4 rounded-lg shadow-lg bg-fuchsia-500">
          <%= bol %>
        </div>
      <% end %>
    </div>
  </div>

  <% if action_name != "show" %>
    <%= link_to "Show this song", song, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this song", edit_song_path(song), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/songs/edit.html.erb
<div class="mx-auto w-full">
  <h1 class="font-bold text-base">Editing song</h1>

  <%= render "form", song: @song %>

  <%= link_to "Show this song", @song, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to songs", songs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/songs/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Songs</h1>
    <%= link_to "New song", new_song_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="songs" class="min-w-full">
    <%= render @songs %>
  </div>
</div>

app/views/songs/new.html.erb
<div class="mx-auto w-full">
  <h1 class="font-bold text-base">New song</h1>

  <%= render "form", song: @song %>

  <%= link_to "Back to songs", songs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/songs/show.html.erb
<div class="mx-auto w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @song %>

    <%= link_to "Edit this song", edit_song_path(@song), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this song", song_path(@song), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to songs", songs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>